version: "3.8"

services:
  postgres:
    image: 'postgres:13-alpine'
    container_name: postgres-db
    restart: unless-stopped
    ports:
        - "127.0.0.1:5432:5432"
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: /opt/postgres
    volumes:
        - ./.docker/postgres:/opt/postgres
    networks:
        default:

  pgadmin:
    image: 'dpage/pgadmin4:6'
    container_name: pgadmin
    restart: always
    ports:
        - "127.0.0.1:5050:5050"
    environment:
        PGADMIN_LISTEN_PORT: 5050
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - ./.docker/pgadmin:/var/lib/pgadmin:rw
    depends_on:
        - postgres
    networks:
        default:

  nginx:
    image: 'nginx:alpine'
    container_name: webserver
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./conf.d/ssl:/etc/nginx/ssl:ro
        - ./.docker/nginx/logs:/var/log/nginx
    networks:
        default:
    depends_on:
        - pgadmin

networks:
    default:
